"""Tests for the general-purpose rewriting tool and endpoint."""

from __future__ import annotations

import json
from unittest.mock import AsyncMock, patch

import pytest

from app.tools.general_rewriter import general_rewrite, _parse_variations


# ---------------------------------------------------------------------------
# _parse_variations
# ---------------------------------------------------------------------------

def test_parse_variations_valid_json():
    raw = json.dumps(["one", "two", "three"])
    assert _parse_variations(raw) == ["one", "two", "three"]


def test_parse_variations_more_than_three():
    raw = json.dumps(["a", "b", "c", "d"])
    assert len(_parse_variations(raw)) == 3


def test_parse_variations_fallback_to_raw():
    raw = "Just a plain string, not JSON."
    result = _parse_variations(raw)
    assert len(result) == 1
    assert result[0] == raw


def test_parse_variations_markdown_code_block():
    raw = '```json\n["first", "second", "third"]\n```'
    result = _parse_variations(raw)
    assert len(result) == 3
    assert result[0] == "first"


# ---------------------------------------------------------------------------
# general_rewrite — skipped case
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
async def test_general_rewrite_short_text():
    """Text that's too short should be returned unchanged."""
    result = await general_rewrite("Hi")
    assert result["skipped"] is True
    assert result["original"] == "Hi"
    assert len(result["variations"]) == 1


# ---------------------------------------------------------------------------
# general_rewrite — happy path (mocked OpenAI)
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
@patch("app.tools.general_rewriter._call_openai", new_callable=AsyncMock)
async def test_general_rewrite_happy_path(mock_openai):
    mock_openai.return_value = json.dumps([
        "Rewritten version A.",
        "Rewritten version B.",
        "Rewritten version C.",
    ])
    result = await general_rewrite(
        text="The quick brown fox jumps over the lazy dog.",
        mode="paraphrase",
        tone="neutral",
        strength="medium",
    )
    assert result["skipped"] is False
    assert len(result["variations"]) == 3
    assert result["mode"] == "paraphrase"
    assert result["tone"] == "neutral"
    assert result["strength"] == "medium"
    assert result["elapsed_s"] >= 0
    mock_openai.assert_called_once()


@pytest.mark.asyncio
@patch("app.tools.general_rewriter._call_openai", new_callable=AsyncMock)
async def test_general_rewrite_humanize_mode(mock_openai):
    mock_openai.return_value = json.dumps([
        "Human v1.", "Human v2.", "Human v3.",
    ])
    result = await general_rewrite(
        text="This text was clearly generated by an artificial intelligence model.",
        mode="humanize",
        tone="friendly",
        strength="high",
    )
    assert result["mode"] == "humanize"
    assert result["tone"] == "friendly"
    assert result["strength"] == "high"
    assert len(result["variations"]) == 3


# ---------------------------------------------------------------------------
# API endpoint
# ---------------------------------------------------------------------------

@pytest.mark.asyncio
@patch("app.tools.general_rewriter._call_openai", new_callable=AsyncMock)
async def test_general_rewrite_endpoint(mock_openai):
    mock_openai.return_value = json.dumps(["v1", "v2", "v3"])
    from starlette.testclient import TestClient
    from app.main import app

    client = TestClient(app)
    resp = client.post("/api/v1/rewrite/general", json={
        "text": "The economy of the country has been growing steadily over the years.",
        "mode": "formal",
        "tone": "professional",
        "strength": "high",
    })
    assert resp.status_code == 200
    data = resp.json()
    assert len(data["variations"]) == 3
    assert data["mode"] == "formal"
    assert data["skipped"] is False
