"""AI detection agent — detects AI-generated text.

Delegates all computation to the ai_detection_tool.
The agent only handles orchestration and interpretation.
"""

from __future__ import annotations

from app.agents.base_agent import BaseAgent
from app.config import settings
from app.models.schemas import AgentInput, AgentOutput, FlaggedPassage
from app.tools.ai_detection_tool import detect_ai_text
from app.tools.content_extractor_tool import chunk_text


class AIDetectionAgent(BaseAgent):
    """Identifies whether text was generated by an AI model."""

    @property
    def name(self) -> str:
        return "ai_detection_agent"

    async def _analyze(self, agent_input: AgentInput) -> AgentOutput:
        self.logger.info(
            "ai_detection_started",
            document_id=agent_input.document_id,
        )

        # --- 1. Chunk the text ------------------------------------------------
        chunk_result = chunk_text(agent_input.text, chunk_size=settings.chunk_size)
        chunks = agent_input.chunks or chunk_result["chunks"]

        # --- 2. Run AI detection (via ai_detection_tool) ----------------------
        result = await detect_ai_text(agent_input.text, chunks=chunks)

        # --- 3. Build flagged passages from tool output -----------------------
        flagged: list[FlaggedPassage] = []
        for item in result.get("flagged_chunks", []):
            flagged.append(FlaggedPassage(
                text=item["text"],
                similarity_score=min(result["score"] / 100.0, 1.0),
                source="ai_detection_heuristic",
                reason=item.get("reason", "Suspected AI-generated text"),
            ))

        self.logger.info(
            "ai_detection_complete",
            document_id=agent_input.document_id,
            score=result["score"],
            confidence=result["confidence"],
            flagged_count=len(flagged),
        )

        return AgentOutput(
            agent_name=self.name,
            score=result["score"],
            confidence=result["confidence"],
            flagged_passages=flagged,
            details={
                "status": "completed",
                "indicators": result.get("indicators", {}),
                "elapsed_s": result.get("elapsed_s", 0.0),
            },
        )
